### ISSUE TITLE
Fix up convergence checking

### ISSUE THREAD

**Issue by ahwillia** [degleris1/cmfpy#11]
Create flexible convergence checking. Probably default to percent change in error:

```python
(last_error - curr_error) / last_error

(last_error - curr_error) / norm(data)
```

https://github.com/degleris1/cmfpy/blob/e6c3d314a196a5c98117d8638cee921ad1fe0557/cmfpy/algs/frame.py#L41

**Comment by degleris1** [comment]
For now, we have switched to using the score. This is normalized by the size of the data and should suffice.
